theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
title: bold360 Android SDK
baseurl: "/bold360-mobile-docs-android"
url: "https://logmein-bold-mobile.github.io"
color_scheme: android-scheme
plugins: 
  - jekyll-redirect-from

permalink: pretty

logo: "/assets/images/genesys-bold360.png"

footer_content: ""

back_to_top: true
back_to_top_text: "To top"
